# Generated by Django 3.1 on 2020-10-05 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STR_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='patient_with_reccord',
        ),
        migrations.RemoveField(
            model_name='record',
            name='therapist',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.DeleteModel(
            name='Therapist',
        ),
    ]
