# Generated by Django 3.1 on 2020-10-10 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STR_app', '0008_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
