# Generated by Django 3.1 on 2020-10-12 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STR_app', '0012_auto_20201012_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='therapist',
        ),
        migrations.RemoveField(
            model_name='record',
            name='patient_with_record',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.DeleteModel(
            name='Therapist',
        ),
    ]
