# Generated by Django 3.1 on 2020-10-08 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STR_app', '0005_auto_20201008_0106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='record_share',
            new_name='share_record',
        ),
    ]
