# Generated by Django 3.1 on 2020-10-08 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STR_app', '0006_auto_20201008_0506'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
